"""
This file will be used for adding the constant variables.
"""
# Mapping Connection Constants
SOURCE_CONN = "source_conn"
TARGET_CONN = "target_conn"
SCHEMA_NAME = "schema_name"
TABEL_NAME = "table_name"
TARGET_SCHEMA_NAME = "target_schema_name"
TARGET_TABLE_NAME = "target_table_name"
RESULT_HANDLER = "result_handler"
HOST = "host"
USER = "user"
PASSWORD = "password"
DATABASE = "database"
PORT = "port"
SOURCE_TYPE = "source_type"
PROJECT_ID = "project_id"
PCT_THRESHOLD = "pct_threshold"
THRESHOLD = "threshold"

AGGREGATES = "aggregates"
SOURCE_COLUMN = "source_column"
TARGET_COLUMN = "target_column"

# Mapping DB Constants
SOURCE_DATABASE = "source_database"
TARGET_DATABASE = "target_database"
DB_HOST = "db_host"
DB_USER = "db_user"
DB_PASSWORD = "db_password"
DB_NAME = "db_name"
DB_PORT = "db_port"
DB_TYPE = "db_type"


# DVT Response
VALIDATION_TYPE = "validation_type"
AGGREGATION_TYPE = "aggregation_type"
SOURCE_TABLE_NAME = "source_table_name"
SOURCE_AGG_VALUE = "source_agg_value"
TARGET_AGG_VALUE = "target_agg_value"
DIFFERENCE = "difference"
PCT_DIFFERENCE = "pct_difference"
VALIDATION_STATUS = "validation_status"
