apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dvt
  name: test-dvt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvt
  template:
    metadata:
      labels:
        app: dvt
    spec:
      serviceAccountName: workload-identity-ksa
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
      - image: gcr.io/m2m-wayfair-dev/data-validation@sha256:47ba9e0a331e2e9777baa766fc053f652f53906a77b4a1a3ba5914a1e51b4e11
        name: data-validation
        env:
          - name: PORT
            value: "8080"
        ports:
        - name: http
          containerPort: 8080
        resources: 
          limits:
            cpu: 500m
            memory: 2Gi
      - image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
        name: cloud-sql-proxy
        args:
          - "--auto-iam-authn"
          # Enable structured logging with LogEntry format:
          - "--structured-logs"
          # Replace DB_PORT with the port the proxy should listen on
          #- "--port=5432"
          #- "m2m-wayfair-dev:us-east1:m2m-wayfair-dev-49bfb53c"
          - "m2m-wayfair-dev:us-east1:striim-mdr?port=5433"
          - "m2m-wayfair-dev:us-east1:m2m-wayfair-dev-49bfb53c?port=5432"  
        securityContext:
          runAsNonRoot: true
        # resources:
  
      

